add_newline = false

format = """
[$username@$hostname](green) \
$directory\
$git_branch\
$git_status\
$docker_context\
$conda\
$aws\
$gcloud\
$env_var\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$status\
$time\
$character"""

[conda]
ignore_base = false

[directory]
truncation_length = 20
truncation_symbol = "…/"

[git_branch]
symbol = ""

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
ssh_only = false
format = "[$hostname](green)"

[time]
format = "[$time]($style) "
disabled = false

[username]
format = "[$user](green)"
show_always = true
